# By default, this image creates
# no authenication restrictions
# and should be used for development only
FROM postgres:9.4
MAINTAINER 'Chris George <chris@leftronic.com>'

ADD init-database.sh /docker-entrypoint-initdb.d/
