redis:
  image: redis:latest
  environment:
    VIRTUAL_HOST: redis.docker
db:
  build: ./docker/postgres/.
  env_file:
    - ./docker/postgres/env
  environment:
    VIRTUAL_HOST: db.docker
  ports:
    - 5432:5432
api:
  build: .
  environment:
    VIRTUAL_HOST: api.docker
  command: python manage.py runserver --threaded --debug --reload -h 0.0.0.0 -p 9000
  env_file:
    - .envrc
  volumes:
    - .:/app
  working_dir: /app/
  ports:
    - 9000:9000
  links:
    - redis
    - db

